config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "activate"
      post "upgrade"
    end
  end
  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :update, :destroy, :show] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :update, :show, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:create, :destroy]
end

app/models/note.rb
class Note < ApplicationRecord
  validates :note, presence: true

  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :render_403_if_try_to_delete_now_own_note, only: [:destroy]

  def new
    render "new"
  end

  def create
    note = Note.new(note_params)
    note.user_id = current_user.id

    if note.save
      redirect_to track_url(note.track_id)
    else
      redirect_to new_track_note_url(note.track_id)
    end
  end

  def destroy
    note = Note.find_by(id: params[:id])
    note.destroy
    redirect_to track_url(note.track_id)
  end

  private
  def note_params
    params.require(:note).permit(:note, :track_id)
  end
end

app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="post">
  <%= csrf_token %>

  <input type="hidden" name="note[track_id]" value="<%= track_id %>" />
  <label for="note">Note</label>
  <textarea id="note" name="note[note]"></textarea>
  <button>create</button>
</form>

app/views/notes/_note.html.erb
<div class="note">
  <p><%= note.note %></p>
  <p><%= note.user.email %></p>

  <% if current_user.admin || current_user.have_note?(note) %>
    <form action="<%= note_url(note.id) %>" method="post">
      <%= csrf_token %>
      <input type="hidden" name="_method" value="delete">
      <button>Destroy</button>
    </form>
  <% end %>

</div>

app/views/notes/new.html.erb
<%= render "form", track_id: params[:track_id] %>