config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "activate"
      post "upgrade"
    end
  end
  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :update, :destroy, :show] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :update, :show, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:create, :destroy]
end

app/models/track.rb
class Track < ApplicationRecord
  TRACK_TYPES = [
    "regular",
    "bonus"
  ]

  validates :title, :ord, :track_type, presence: true
  validates :track_type, inclusion: TRACK_TYPES

  has_many :notes
  belongs_to :album
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :redirect_if_not_login, only: [:new, :create, :edit, :update, :show, :destroy]
  def new
    @track = Track.new(track_type: "bonus")
    render "new"
  end

  def create
    track = Track.new(track_params)

    if track.save
      render json: track
    else
      render json: {"error": track.errors.full_messages}
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    @albums = Album.all
    render "edit"
  end

  def update
    track = Track.find_by(id: params[:id])

    if track.update(track_params)
      redirect_to bands_url
    else
      redirect_to bands_url
    end
  end

  def show
    @track = Track.eager_load(:notes, notes: :user).find_by(id: params[:id])

    if @track
      render "show"
    else
      redirect_to bands_url
    end
  end

  def destroy
    track = Track.find_by(id: params[:id])
    album_id = track.album_id
    track.destroy

    redirect_to album_url(album_id)
  end

  def track_params
    params.require(:track).permit(:title, :ord, :lyrics, :track_type, :album_id)
  end
end

app/helpers/track_helper.rb
module TrackHelper
  def ugly_lyrics(lyrics)
    lyrics_lines = lyrics.split("\n")
    result = lyrics_lines.map { |line| "&#9835 " + h(line) }.join("\n")
    result.html_safe
  end
end

app/views/tracks/_form.html.erb
<% track = track %>
<% action_url = track.persisted? ? track_url(track) : tracks_url%>
<% form_button_title = track.persisted? ? "Update" : "Create" %>

<form action="<%= action_url %>"  method="post">
  <%= csrf_token %>

  <% if track.persisted? %>
    <input type="hidden" name="_method" value="patch">

    <label for="album">Album</label>
    <select id="album" name="track[album_id]">
      <%= @albums.each do |album| %>
        <option value="<%= album.id %>" <% if @track.album_id == album.id %> selected <% end %>>
          <%= album.title %>
        </option>
      <% end %>
    </select>
  <% else %>
    <input type="hidden" name="track[album_id]" value="<%= params[:album_id] %>" />
  <% end %>


  <label for="title">Title</label>
  <input id="title" type="text" name="track[title]" value="<%= @track.title %>" />
  <br />

  <label for="ord">Ord</label>
  <input id="ord" type="number" name="track[ord]"  value="<%= @track.ord %>">
  <br />


  <label for="lyric">Lyrics</label>
  <textarea id="lyric" name="track[lyrics]"><%= @track.lyrics %></textarea>
  <br />


  <label for="track_type">Track Type</label>
  <select id="track_type" name="track[track_type]">
    <%= Track::TRACK_TYPES.each do |track_type| %>
      <option value="<%= track_type %>" <% if @track.track_type == track_type %> selected <% end %>>
        <%= track_type %>
      </option>
    <% end %>
  </select>
  <br />


  <button><%= form_button_title %></button>
</form>

app/views/tracks/edit.html.erb
<%= render "form", track: @track%>

app/views/tracks/new.html.erb
<%= render "form", track: @track%>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<p><%= @track.ord %></p>

<pre><%= ugly_lyrics(@track.lyrics) %></pre>

<%= show_if_current_user_is_admin do %>
  <a href="<%= edit_track_url %>">Edit</a>

  <form action="<%= track_url(@track) %>" method="post">
    <%= csrf_token %>
    <input type="hidden" name="_method" value="delete" />
    <button>Delete</button>
  </form>
<% end %>


<h2>Notes</h2>

<% @track.notes.each do |note| %>
  <%= render note %>
<% end %>

<a href="<%= new_track_note_url(@track) %>">Add note</a>