config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "activate"
      post "upgrade"
    end
  end
  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :update, :destroy, :show] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :update, :show, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
  RECORD_TYPES = [
    "studio",
    "live"
  ]

  attr_reader :record_type
  validates :title, :year, presence: true
  validates :record_type, inclusion: RECORD_TYPES
  before_save :set_studio

  has_many :tracks, dependent: :destroy
  belongs_to :band

  def record_type=(record_type)
    @record_type = record_type
  end

  def set_studio
    self.studio = (@record_type == "studio")
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_if_not_login, only: [:new, :create, :edit, :update, :destroy, :show]

  def new
    render "new"
  end

  def create
    album = Album.new(album_params)

    if album.save
      render json: album
    else
      render json: album.errors.full_messages, status: :unprocessable_content
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])

    if @album
      @bands = Band.all
      render "edit"
    else
      redirect_to bands_url
    end
  end

  def update
    album = Album.find_by(id: params[:id])
    album.update(album_params)
    redirect_to bands_url
  end

  def destroy
    album = Album.find_by(id: params[:id])
    band_id = album.band_id

    if album
      album.destroy
      redirect_to band_url(band_id)
    else
      redirect_to bands_url
    end
  end

  def show
    @album = Album.find_by(id: params[:id])

    if @album
      @tracks = @album.tracks
      render "show"
    else
      redirect_to bands_url
    end
  end

  private
  def album_params
    params.require(:album).permit(:year, :title, :band_id, :record_type)
  end
end

app/views/albums/_album.html.erb
<a href="<%= album_url(album) %>"><%= album.title %></a>
<%= show_if_current_user_is_admin do %>
  <a href="<%= edit_album_url(album) %>">Edit</a>
  
  <form action="<%= album_url(album) %>" method="post">
    <%= csrf_token %>

    <input type="hidden" name="_method" value="delete">
    <button>delete</button>
  </form>
<% end %>

app/views/albums/edit.html.erb
<form action="<%= album_url(@album) %>" method="post">
  <%= csrf_token %>

  <input type="hidden" name="_method" value="patch">

  <label for="band">Band</label>
  <select id="band" name="album[band_id]">
    <% @bands.each do |band| %>
      <option value="<%= band.id %>"><%= band.name %></option>
    <% end %>
  </select>

  <label for="title">Title</label>
  <input id="title" type="text" name="album[title]" value="<%= @album.title %>" />

  <label for="year">Year</label>
  <input id="year" type="number" name="album[year]" value="<%= @album.year %>" >

  <input id="record_type" type="radio" name="album[record_type]" value="studio" <% if @album.studio %> checked <% end %> />
  <label for="record_type" >Studio</label>

  <input id="live-record-type" type="radio" name="album[record_type]" value="live" <% unless @album.studio %> checked <% end %>/>
  <label for="live-record-type">Live</label>

  <br>

  <button>Edit</button>
</form>

app/views/albums/new.html.erb
<form action="<%= albums_url %>" method="post">
  <%= csrf_token %>
  <input type="hidden" name="album[band_id]" value="<%= params[:band_id] %>" />

  <label for="title">Title</label>
  <input id="title" type="text" name="album[title]" />

  <label for="year">Year</label>
  <input id="year" type="number" name="album[year]">

  <input id="record_type" type="radio" name="album[record_type]" value="studio" checked >
  <label for="record_type" >Studio</label>

  <input id="record_type" type="radio" name="album[record_type]" value="live" checked >
  <label for="record_type">Live</label>

  <br>

  <button>Create</button>
</form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<p><%= @album.year %></p>

<h2>Tracks</h2>

<% @tracks.each do |track| %>
  <ul>
    <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
  </ul>
<% end %>

<%= show_if_current_user_is_admin do %>
  <a href="<%= new_album_track_url(@album) %>">New</a>
<% end %>