config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "activate"
      post "upgrade"
    end
  end
  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :update, :destroy, :show] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :update, :show, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:create, :destroy]
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :redirect_if_not_login, only: [:index, :create, :edit, :show, :update, :destroy, :new]
  before_action :check_admin_authorization, only: [:create, :edit, :update, :destroy]

  def index
    @bands = Band.all
    render "index"
  end

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to bands_url
    else
      render json: {"errors": band.errors.full_messages}, status: :unprocessable_content
    end
  end

  def edit
    @id = params[:id]
    render "edit"
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def update
    band = Band.find_by(id: params[:id])
    band.update(band_params)

    redirect_to band_url
  end

  def destroy
    band = Band.find_by(id: params[:id])
    band.destroy
    redirect_to bands_url
  end

  def new
    render "new"
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/views/bands/edit.html.erb
<form action="<%= band_path(@id) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= csrf_token %>

  <label for="band">Name</label>
  <input id="band" type="text" name="band[name]" />

  <button>Edit</button>
</form>

app/views/bands/index.html.erb
<% @bands.each do |band| %>
  <ul>
    <li>
      <a href="<%= band_url(band) %>"><%= band.name %></a>

      <%= show_if_current_user_is_admin do %>
          <form action="<%= band_url(band) %>" method="post">
            <input type="hidden" name="_method" value="delete" >
            <%= csrf_token %>
            <button>Destroy</button>
          </form>
        </li>
      </ul>
    <% end %>
<% end %>

<br>
<br>

<%= show_if_current_user_is_admin do %>
  <a href="<%= new_band_url %>">New</a>
<% end %>

app/views/bands/new.html.erb
<form action="<%= bands_url %>" method="post">
  <label for="name">Name</label>
  <input id="name" name="band[name]" type="text" />
  <%= csrf_token %>
  <button>Create</button>
</form>

<a href="<%= bands_url %>">Index</a>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<br>
<br>

<h1>Albums</h1>
<% @band.albums.each do |album| %>
  <ul>
    <li>
      <%= render "albums/album", album: album %>
    </li>
  </ul>
<% end %>

<a href="<%= bands_url %>">Index</a>

<%= show_if_current_user_is_admin do %>
  <a href="<%= edit_band_url %>">Edit</a>
  <a href="<%= new_band_album_url(@band) %>">New Album</a>
<% end %>